Update rebuild.yml

diff --git a/.github/workflows/rebuild.yml b/.github/workflows/rebuild.yml
--- a/.github/workflows/rebuild.yml
+++ b/.github/workflows/rebuild.yml
@@ -1,224 +1,187 @@
----
-name: Rebuild Docker-Documentserver 
-
-run-name: >
-        Rebuild DocumentServer with secure updates for repo: ${{ github.event.inputs.repo }}
+### This workflow setup instance then build and push images ###
+name: Multi-arch build stable
+run-name: ${{ inputs.tag }} (${{ inputs.release_number }})
 
 on:
   workflow_dispatch:
     inputs:
-      repo:
-        type: choice
-        description: Please, choose upload repo..
-        options:
-        - '4test'
-        - 'stable'
+      tag:
+        description: 'Tag for release (ex. 1.2.3.45)'
+        type: string
+        required: true
+      release_number:
+        description: 'Sequence number of the release (ex. x.x.x.<number>)'
+        type: string
+        required: true
+        default: '1'
+      latest:
+        description: 'Push latest tag?'
+        type: boolean
+        required: true
+        default: true
 
-permissions:
-  # All other permissions are set to none
-  contents: read
-  # Technically read access while waiting for images should be more than enough. However,
-  # there is a bug in GitHub Actions/Packages and in case private repositories are used, you get a permission
-  # denied error when attempting to just pull private image, changing the token permission to write solves the
-  # issue. This is not dangerous, because if it is for "ONLYOFFICE/Docker-DocumentServer", only maintainers can use ds-rebuild.yaml
-  # If it is for a fork, then the token is read-only anyway.
-  packages: read
-
-env: 
+env:
   COMPANY_NAME: "onlyoffice"
-  PRODUCT_NAME: "documentserver" 
-  REGISTRY_URL: "https://hub.docker.com/v2/repositories"  
+  PRODUCT_NAME: "documentserver"
+  VERSION: ${{ github.event.inputs.tag }}
+  RELEASE_NUMBER: ${{ github.event.inputs.release_number }}
+  LATEST: ${{ github.event.inputs.latest }}
 
 jobs:
-  rebuild-info:
-    name: "Rebuild-info"
-    runs-on: "ubuntu-22.04"
-    env:
-      REPO_INPUTS: ${{ github.event.inputs.repo }}
-      EVENT: ${{ github.event_name }}
-    outputs: 
-      stable-versions: ${{ steps.selective-checks.outputs.stable-versions }}
-      ucs-versions: ${{ steps.selective-checks.outputs.ucs-versions }}
-      minor-tags: ${{ steps.selective-checks.outputs.minor-tags }}
-      ucs-rebuild-condition: ${{ steps.selective-checks.outputs.ucs-rebuild-condition }}
-      prefix-name: ${{ steps.selective-checks.outputs.prefix-name }}
-      repo: ${{ steps.selective-checks.outputs.repo }}
-    steps:
-      - name: Selective checks
-        id: selective-checks
-        run: |
-            set -e
-
-            REPO=${REPO_INPUTS:-"4test"}
-
-            if [ "${REPO}" == "stable" ]; then
-                 UCS_REBUILD=true
-                 UCS_VERSIONS=($(curl -s -H -X ${REGISTRY_URL}/${COMPANY_NAME}/${PRODUCT_NAME}-ucs/tags/?page_size=100 | \
-                            jq -r '.results|.[]|.name' | grep -oxE '[0-9]{1,}.[0-9]{1,}.[0-9]{1,}.1' || true))
-                 echo "ucs-versions=$(jq -c -n '$ARGS.positional' --args "${UCS_VERSIONS[@]}")" >> "$GITHUB_OUTPUT"
-            elif
-               [ "${REPO}" == "4test" ]; then 
-                 UCS_REBUILD=false
-                 PREFIX_NAME=4testing-
-            fi
-            
-            STABLE_VERSIONS=($(curl -s -H -X ${REGISTRY_URL}/${COMPANY_NAME}/${PRODUCT_NAME}/tags/?page_size=100 | \
-                            jq -r '.results|.[]|.name' | grep -oxE '[0-9]{1,}.[0-9]{1,}.[0-9]{1,}.1' || true))
-                            
-            # When rebuilding stable versions of the document server, 
-            # it is necessary to determine the version from which the 
-            # minor x.x tag will need to be pushed.        
-            
-            VERSIONS=(${STABLE_VERSIONS[@]})
-            for i in {1..10}; do
-                 if [ -z "${VERSIONS}" ]; then
-                     break
-                 else 
-                     TEMPLATE=${VERSIONS[0]%.*.*}
-                     TEMPLATE_MINOR=$(printf -- '%s\n' "${VERSIONS[@]}" | grep -o -m 1 "${VERSIONS[0]%.*.*}.[0-9].[0-9]")
-                     MINOR_TAGS+=(${TEMPLATE_MINOR%.*})
-            
-                     for v in ${MINOR_TAGS[@]}; do
-                          VERSIONS=(${VERSIONS[@]//${v%.*}.*.*})
-                     done
-                 fi
-            done
-            
-            echo "Stable releases that will be rebuilded"
-            echo "--------------------------------------"
-            echo "${STABLE_VERSIONS[@]}"
-            echo
-            echo 
-            echo "Ucs releases that will be rebuilded"
-            echo "-----------------------------------"
-            echo "${UCS_VERSIONS[@]}"
-            
-            echo "stable-versions=$(jq -c -n '$ARGS.positional' --args "${STABLE_VERSIONS[@]}")" >> "$GITHUB_OUTPUT"
-            echo "minor-tags=${MINOR_TAGS[@]}" >> "$GITHUB_OUTPUT"
-            echo "ucs-rebuild-condition=${UCS_REBUILD}" >> "$GITHUB_OUTPUT"
-            echo "prefix-name=${PREFIX_NAME}" >>  "$GITHUB_OUTPUT"
-            echo "repo=${REPO}" >> "$GITHUB_OUTPUT"
-        shell: bash
-
-  re-build-stable:
-    name: "Rebuild stable:${{ matrix.version }} ${{ matrix.edition }}"
-    needs: [rebuild-info]
+  build:
+    name: "Release image: DocumentServer${{ matrix.edition }}"
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
-        type: ["stable"]
+        images: ["documentserver-stable"]
         edition: ["", "-ee", "-de"]
-        version: ${{fromJSON(needs.rebuild-info.outputs.stable-versions)}}
     steps:
       - name: Checkout code 
         uses: actions/checkout@v3
+
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2      
-      - name: Login to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
-     # Determines the new build number based 
-     # on data from the hub.docker registry
-      - name: Declare release number
-        id: release-number
-        env: 
-          REBUILD_VERSION: ${{ matrix.version }}
-        run: |
-          MINOR_VERSION=${REBUILD_VERSION%.*} 
-          LAST_RELEASE=$(curl -s -H -X ${REGISTRY_URL}/${COMPANY_NAME}/${PRODUCT_NAME}/tags/?page_size=100 \
-          | jq -r '.results|.[]|.name' | grep -Eo -m1 "${MINOR_VERSION}.[0-9]{1,}")
-          LAST_RELEASE=${LAST_RELEASE#*.*.*.}
-          echo "release-number=$((LAST_RELEASE+1))" >> "$GITHUB_OUTPUT"   
-        shell: bash  
-    #  Note: Rebuilding images with an 
-    #  extra layer to update security and 
-    #  all dependencies. Update tags got +1 to previous release.
-      - name: Re-build documentserver-stable
-        env:
-          MINOR_TAGS_ST: ${{ needs.rebuild-info.outputs.minor-tags }}
-          VERSION: ${{ matrix.version }}
-          RELEASE_NUMBER: ${{ steps.release-number.outputs.release-number }}
-          PREFIX_NAME: ${{ needs.rebuild-info.outputs.prefix-name }}
-          REPO: ${{ needs.rebuild-info.outputs.repo }}
-          PRODUCT_EDITION: ${{ matrix.edition }}
-        run: |
-            set -eux
-            export PULL_TAG=${VERSION}
-            export TAG=${VERSION%.*}.${RELEASE_NUMBER}
-            export SHORTER_TAG=${VERSION%.*}
-            export SHORTEST_TAG=${VERSION%.*.*}
-            
-            if [ "${REPO}" == "stable" ]; then
-                 MINOR_TAGS=(${MINOR_TAGS_ST})
-                 for v in ${MINOR_TAGS[@]}; do
-                     if [ "${SHORTER_TAG}" == "${v}" ]; then
-                         export PUSH_MAJOR="true"
-                     fi
-                 done
-                 if [ "${SHORTER_TAG}" == "${MINOR_TAGS[0]}" ]; then
-                     export LATEST="true"
-                 fi
-            fi
-            docker buildx bake -f docker-bake.hcl documentserver-stable-rebuild --push
-        shell: bash
-  re-build-ucs:
-    name: "Rebuild ucs: ${{ matrix.version }} ${{ matrix.edition }}"
-    if: needs.rebuild-info.outputs.ucs-rebuild-condition == 'true'
-    needs: [rebuild-info]
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        type: ["ucs"]
-        edition: ["", "-ee"]
-        version: ${{fromJSON(needs.rebuild-info.outputs.ucs-versions)}}
-    steps:
-      - name: Checkout code 
-        uses: actions/checkout@v3
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
+     
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
-      # Determines the new build number based 
-      # on data from the hub.docker registry
-      - name: Declare release number
-        id: release-number
-        env: 
-          REBUILD_VERSION: ${{ matrix.version }}
+
+      - name: Verify Docker Hub access
         run: |
-          MINOR_VERSION=${REBUILD_VERSION%.*} 
-          LAST_RELEASE=$(curl -s -H -X ${REGISTRY_URL}/${COMPANY_NAME}/${PRODUCT_NAME}/tags/?page_size=100 \
-                        | jq -r '.results|.[]|.name' | grep -Eo -m1 "${MINOR_VERSION}.[0-9]{1,}")
-          LAST_RELEASE=${LAST_RELEASE#*.*.*.}
-          echo "release-number=$((LAST_RELEASE+1))" >> "$GITHUB_OUTPUT"
-        shell: bash       
-      #  Note: Rebuilding images with an 
-      #  extra layer to update security and 
-      #  all dependencies. Update tags +1 to previous release.
-      - name: Re-build documentserver-ucs
-        env: 
-          VERSION: ${{ matrix.version }}
-          RELEASE_NUMBER: ${{ steps.release-number.outputs.release-number }}
+          echo "Verifying access to target repository..."
+          docker pull hello-world
+          echo "Docker Hub authentication successful"
+        shell: bash
+
+      - name: Build documentserver-release
+        env:
+          TARGET: ${{ matrix.images }}
           PRODUCT_EDITION: ${{ matrix.edition }}
         run: |
-            set -eux
-            export PULL_TAG=${VERSION}
-            export TAG=${VERSION%.*}.${RELEASE_NUMBER}
-            export SHORTER_TAG=${VERSION%.*}
-            export SHORTEST_TAG=${VERSION%.*.*}
+          set -eux
+          TESTING_IMAGE=${COMPANY_NAME}/4testing-${PRODUCT_NAME}${PRODUCT_EDITION}
+          export PRODUCT_EDITION
+          export PULL_TAG="${VERSION}"
+          export TAG="${VERSION%.*}.${RELEASE_NUMBER}"
+          export SHORTER_TAG="${VERSION%.*}"
+          export SHORTEST_TAG="${VERSION%.*.*}"
           
-            export UCS_REBUILD=true
-            export UCS_PREFIX=-ucs
+          # Trim any whitespace from variables
+          PULL_TAG=$(echo "${PULL_TAG}" | xargs)
+          TAG=$(echo "${TAG}" | xargs)
+          SHORTER_TAG=$(echo "${SHORTER_TAG}" | xargs)
+          SHORTEST_TAG=$(echo "${SHORTEST_TAG}" | xargs)
           
-            docker buildx bake -f docker-bake.hcl documentserver-stable-rebuild --push
+          # Re-export cleaned variables
+          export PULL_TAG
+          export TAG
+          export SHORTER_TAG
+          export SHORTEST_TAG
+          
+          echo "Building with the following tags:"
+          echo "PULL_TAG: '${PULL_TAG}'"
+          echo "TAG: '${TAG}'"
+          echo "SHORTER_TAG: '${SHORTER_TAG}'"
+          echo "SHORTEST_TAG: '${SHORTEST_TAG}'"
+          echo "Target repository: ${COMPANY_NAME}/${PRODUCT_NAME}${PRODUCT_EDITION}"
+          
+          # Validate tag format
+          if [[ "${TAG}" =~ [[:space:]] ]]; then
+            echo "ERROR: TAG contains whitespace: '${TAG}'"
+            exit 1
+          fi
+          
+          # Attempt to build and push
+          if docker buildx bake -f docker-bake.hcl "${TARGET}" --push; then
+            echo "DONE: Build success >> exit with 0"
+            exit 0
+          else
+            echo "ERROR: Build or push failed"
+            echo "Please verify:"
+            echo "1. Docker Hub credentials have push access to ${COMPANY_NAME}/${PRODUCT_NAME}${PRODUCT_EDITION}"
+            echo "2. The repository ${COMPANY_NAME}/${PRODUCT_NAME}${PRODUCT_EDITION} exists"
+            echo "3. The authentication token has sufficient permissions"
+            exit 1
+          fi
+        shell: bash
+
+  build-nonexample:
+    name: "Release image: DocumentServer${{ matrix.edition }}-nonExample"
+    runs-on: ubuntu-latest
+    needs: [build]
+    if: ${{ false }}
+    strategy:
+      fail-fast: false
+      matrix:
+        images: ["documentserver-nonexample"]
+        edition: ["", "-ee", "-de"]
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v2
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+
+      - name: build image
+        env:
+          TARGET: ${{ matrix.images }}
+          PRODUCT_EDITION: ${{ matrix.edition }}
+        run: |
+          set -eux
+          export PULL_TAG=${VERSION%.*}.${RELEASE_NUMBER}
+          export TAG=${VERSION%.*}.${RELEASE_NUMBER}
+          docker buildx bake -f docker-bake.hcl "${TARGET}" --push
+        shell: bash
+
+  build-ucs-ubuntu20:
+    name: "Release image: DocumentServer${{ matrix.edition }}-ucs"
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        edition: ["", "-ee"]
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v2
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+
+      - name: build UCS
+        env:
+          PACKAGE_BASEURL: ${{ secrets.REPO_BASEURL }}
+          PRODUCT_EDITION: ${{ matrix.edition }}
+        run: |
+           set -eux
+           export DOCKERFILE=Dockerfile
+           export BASE_VERSION=20.04
+           export PG_VERSION=12
+           export PACKAGE_SUFFIX=
+           export TAG=${VERSION%.*}.${RELEASE_NUMBER}
+           export PACKAGE_VERSION=$( echo ${VERSION} |  sed -E 's/(.*)\./\1-/')
+           docker buildx bake -f docker-bake.hcl documentserver-ucs --push
         shell: bash
